### ISSUE TITLE
After adding mongo-extensions meteor refuses to run

### ISSUE THREAD

**Issue by pinfake** [jhoxray/meteor-mongo-extensions#3]
I just installed your extension using meteorite, and trying to start meteor on my project's folder gives an error. 
Most probably I'm doing something wrong, 
Could you help me out?

Thanks in advance.

$ mrt add mongodb-aggregation
smart.json changed.. installing from smart.json
✓ select2
    tag: https://github.com/nate-strauser/meteor-select2.git#v3.4.0
✓ font-awesome
    tag: https://github.com/nate-strauser/meteor-font-awesome.git#v3.2.0
✓ mongodb-aggregation
    tag: https://github.com/jhoxray/meteor-mongo-extensions.git#v0.1.5

Done installing smart packages

$ meteor
[[[[[ ~/devel/projects/laddermania ]]]]]

=> Meteor server running on: http://localhost:3000/

/Users/pin/devel/projects/laddermania/.meteor/local/build/server/server.js:337
  }).run();
     ^
TypeError: Object #<Object> has no method 'require'
    at app/packages/mongodb-aggregation/server.coffee.js:4:31
    at /Users/pin/devel/projects/laddermania/.meteor/local/build/server/server.js:298:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/pin/.meteor/tools/d699ad29da/lib/node_modules/underscore/underscore.js:78:11)
    at run (/Users/pin/devel/projects/laddermania/.meteor/local/build/server/server.js:239:7)
=> Exited with code: 1
=> Meteor server restarted

**Comment by pinfake** [comment]
I didn't notice it was just the pull they are asking you for. Closed it.
